### ISSUE TITLE
Add page for CSS Nesting

### ISSUE THREAD

**Issue by aetinx** [mdn/mdn#427] opened 2023-07-15 16:30 UTC
### Proposal

There would be a page about CSS Nesting and it's support on browsers.

Example: https://developer.chrome.com/articles/css-nesting/

### Task list

- [ ] Do some research
- [ ] Put together a page
- [ ] Publish it

### Additional information

https://www.w3.org/TR/css-nesting-1/
https://caniuse.com/css-nesting

### Are you willing to support this work?

Yes

### Depends on

Not that I know of.

**Comment by dipikabh** [comment] 2023-08-29 20:58
Closing this as a duplicate of https://github.com/mdn/content/issues/27180.

**Closed by dipikabh** 2023-08-29 20:58 UTC
Labels: needs triage, proposal
