### ISSUE TITLE
CSS Nesting Documentation

### ISSUE THREAD

**Issue by heyitsdoodler** [mdn/mdn#413] opened 2023-06-05 21:43 UTC
### Proposal

Nested CSS rules are now supported on most major browsers. As MDN is one of the premier sources on features of HTML, JavaScript, and CSS it would make sense for the Web Docs to cover this topic.

### Task list

- Create page for CSS nesting
- Write description and examples of CSS nesting
- Provide current browser support/compatibility

### Additional information

https://drafts.csswg.org/css-nesting/
https://caniuse.com/css-nesting
https://developer.chrome.com/articles/css-nesting/

### Are you willing to support this work?

Yes, however I'm fairly unfamiliar with the contribution process for MDN Web Docs.

**Comment by dipikabh** [comment] 2023-08-29 20:59
Closing this as a duplicate of https://github.com/mdn/content/issues/27180.

**Closed by dipikabh** 2023-08-29 20:59 UTC
Labels: needs triage, proposal
