### ISSUE TITLE
Document.execCommand() marked obsolete

### ISSUE THREAD

**Issue by jkovzels** [mdn/mdn#94] opened 2020-07-02 10:56 UTC
HI, I wonder why `Document.execCommand()` ([link](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) )is marked obsolete. I've tried to find the source of this info and can not find any confirmation that it is obsolete.  Plus, a lot of MDN articles refer to  `execCommand` without a mention that it is obsolete. Can you please clarify if it is ok to so still use it or not?

**Comment by Elchi3** [comment] 2020-07-02 12:38
Duplicate of https://github.com/mdn/sprints/issues/3460

**Closed by Elchi3** 2020-07-02 12:38 UTC
