### ISSUE TITLE
About the Chinese translation of the Intersection Observer page in the document

### ISSUE THREAD

**Issue by eBaby-C** [mdn/mdn#330] opened 2023-01-05 11:00 UTC
### Proposal

![image](https://user-images.githubusercontent.com/78027982/210764141-325b8274-68c6-4eca-82eb-2a5d3f7692f4.png)
[https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver](url)

Please check the translation of "root" in this page
There are two extra * in the Chinese page
May I ask if this ** is used as Markdown syntax to express emphasis?

### Task list

- [ ]

**Comment by nschonni** [comment] 2023-01-05 17:42
If you use the [Report a problem with this content on GitHub](https://github.com/mdn/translated-content/issues/new?template=page-report-zh-cn.yml&mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fzh-CN%2Fdocs%2FWeb%2FAPI%2FIntersectionObserver&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EPage+report+details%3C%2Fsummary%3E%0A%0A*+Folder%3A+%60zh-cn%2Fweb%2Fapi%2Fintersectionobserver%60%0A*+MDN+URL%3A+https%3A%2F%2Fdeveloper.mozilla.org%2Fzh-CN%2Fdocs%2FWeb%2FAPI%2FIntersectionObserver%0A*+GitHub+URL%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fblob%2Fmain%2Ffiles%2Fzh-cn%2Fweb%2Fapi%2Fintersectionobserver%2Findex.md%0A*+Last+commit%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fcommit%2Fc16d394a008b6896c078cb1b098df67166db0747%0A*+Document+last+modified%3A+2022-10-02T22%3A33%3A30.000Z%0A%0A%3C%2Fdetails%3E) link at the bottom of the page, it will create an issue in the correct repo for the translations. This isn't the right place, but the issue is some malformed markdown for a bold section

**Comment by yin1999** [comment] 2023-02-10 12:37
> Fixed by [mdn/translated-content#10967](https://github.com/mdn/translated-content/pull/10967).

Hi @queengooborg, could you help to close this issue?

**Comment by queengooborg** [comment] 2023-02-10 12:38
Sure thing -- closing and also transferring to `translated-content`!

**Closed by queengooborg** 2023-02-10 12:38 UTC
Labels: needs triage, proposal
